apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-and-test-ocp
spec:
  params:
    - name: test-id
      type: string
    - name: test-name
      type: string
    - name: ocp-version
      type: string
    - name: ocp-login-command
      type: string
      description: ""
  steps:
    - name: upload
      image: quay.io/konflux-qe-incubator/konflux-qe-tools@sha256:ad94717d69e5d192a92b0b9b6cda4223940303f4ff297ea2b69e7cddb94ff7d5
      env:
        - name: TEST_ID
          value: $(params.test-id)
        - name: TEST_NAME
          value: $(params.test-name)
      script: |
        #!/bin/sh
        echo -e "Deploying Ephemeral OpenShift cluster for test with ID: '${TEST_ID}' and name: '${TEST_NAME}'"
        $(params.ocp-login-command)
        oc whoami
        oc get po -A
